FROM node:22.14.0-alpine3.21

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY server ./server

ENV API_HOST=0.0.0.0
ENV API_PORT=3001
EXPOSE 3001

USER node

CMD ["node", "server/index.mjs"]
